In [1]:
from context import cpm


import pandas as pd

from cpm.variables import *

import cpm.functions as f

import cpm.agenda as a

import gspread

import gspread_dataframe as gs_df

from IPython.display import display

# Every time we change a module they are reload before executing 
%reload_ext autoreload
%autoreload 2

## Carrega Planilhas

In [2]:
turmas = f.load_turmas("J23_2019_2S_Feedback")

prefix = r"https://drive.google.com/open?id="

for k,v in turmas.items():
    print(k+"\t", prefix+v.id)

G2	 https://drive.google.com/open?id=1NeWrIr9RPRvxOZG6Bo9m6riNBugGdhvWS5GU9vPwV4w
J	 https://drive.google.com/open?id=12A_vtLdBEjnhWnabObF6Kf_-S_Ho9-um6eYhbh4kUVw
I	 https://drive.google.com/open?id=1EeJeACqfzyZLasxJCTqAV2HcCDjR9yYN4rmyZNVcod0
C2	 https://drive.google.com/open?id=1rXYyAWnr6msLlV2NQCxGWHeA80UoLux6IYWom8fmj4Q
D1	 https://drive.google.com/open?id=11A-i4bLysW29I96Y6b8y8JAuhWZu3AF0ohUdxspcjmI
B1	 https://drive.google.com/open?id=1q9oObH8cHl3CMAWcpnecGqy36WwKkdyvDUeDOXg5KNU
G1	 https://drive.google.com/open?id=1j7b9iP54T8WSv7fingntuFdLwY84JjW5jRLDpucPU0Y
B2	 https://drive.google.com/open?id=1t9WtLqGqCXuFa2MtGGOF_Uhh4Ia93fPBZ5NWuqlRc_k
F	 https://drive.google.com/open?id=1SYH1p87h0MiPrz9rhO-oicPc89rWDZb_Ik32NSM8pYM
D2	 https://drive.google.com/open?id=1IZ6LVygcbQbzUpAOxm-BeE5-NrEhDdPF8nF5wL8cqgU
E2	 https://drive.google.com/open?id=1QKV9DJPg4csGxN-Kr_Qt_eS00mQVtjHRYd0WS8vCwd0
H	 https://drive.google.com/open?id=1ojIYpXr5cLX8hvbNFPQZBOTi82f0L0cKP-xCTg1bDkY
C1	 https://drive.google.com/open?id=1LL4MwbcBd9NbtybWX0BXy58Xl58ch_rxF2TpsbFNdTY
A1	 https://drive.google.com/open?id=1xC1aSiWOHLDBdYTbqKQnKJrqZOtROdcYZmKBmSwt7p0
E1	 https://drive.google.com/open?id=19iX6gBNOZr-B1MOO764nkV2WzA-4ofM-zEXLU02Z0dU

### Lista de Presença

In [6]:
for name, sh in turmas.items():
    # Carrega Lista de Presença
    wb = f.load_wb_from_sheet(sh.title, "Lista de Presença")
    
    nomes = wb.range('C4:C28')
    
    # Select a range
    situacao = wb.range('D4:D28')
    
    for nome, sit in zip(nomes, situacao):
        if nome.value != "" and sit.value == "":
            sit.value = "Ativo"
   
    # Update in batch
    wb.update_cells(situacao)

###

In [ ]:
datas = """Data
04/08/2019
18/08/2019
25/08/2019
01/09/2019
15/09/2019
22/09/2019
29/09/2019
06/10/2019
20/10/2019
27/10/2019
03/11/2019
10/11/2019
24/11/2019
01/12/2019
08/12/2019
15/12/2019""".split("\n")

for name, sh in turmas.items():
    print(name)    
    wb = f.load_wb_from_sheet(sh.title, "Alocação")
    
    # Select a range
    cell_list = wb.range('A1:A17')

    for cell, value in zip(cell_list, datas):
        cell.value = value

    # Update in batch
    wb.update_cells(cell_list)

In [ ]:
for name, sh in turmas.items():
    print(name)    
    wb = f.load_wb_from_sheet(sh.title, "Alocação")
    
    # Select a range
    cell_list = wb.range('C3:C17')

    for cell in cell_list:
        cell.value = fr"='Parâmetros'!C{cell.row}"        

    # Update in batch
    wb.update_cells(cell_list, "USER_ENTERED")
    
    wb.update_acell("C2", "CANCELADO")

In [ ]:
sheets = f.load_workbooks_from_drive()
sheets

In [16]:
exp = "\'\"&turma&\"\'"
value = fr'=query(IMPORTRANGE(link_alunos, range_alunos), "select Col2,Col3,Col4,Col6,Col9,Col10,Col11,Col12,Col13,Col14, Col15 where Col1 = {exp}")'

for name, sh in turmas.items():
    print(name)
    wb = f.load_wb_from_sheet(sh.title, "Info_Students")
    wb.update_cell(1, 1, value)

C1
C2
B2
A1
J
F
I
H
G2
G1
E2
E1
D2
D1
B1
A2

In [6]:
alocação = f.load_df_from_sheet(ALOCACAO, "Agenda", col_names=COLS_AGENDA + ["Presente"])

In [7]:
alocação.head()

,Data,Aula,Turma,Nome,Telefone,Email Pessoal,Email CPM,Presente
0,2019-02-03,1,F2,Adriana Beltrão Dupita,(11) 984566623,adriana.dupita@gmail.com,adriana.dupita@cidadaopromundo.org,True
1,2019-02-03,1,I,Adriana Fernandes de Araújo,(11) 981615548,adrifaraujo@gmail.com,adriana.araujo@cidadaopromundo.org,True
2,2019-02-03,1,A2,Alexandre Santos de Pinho,(11) 996936609,alexandre.spinho@gmail.com,alexandre.pinho@cidadaopromundo.org,True
3,2019-02-03,1,C1,Allexandre Assis Bighetti,(11) 975346059,allexandrebighetti@hotmail.com,allexandre.bighetti@cidadaopromundo.org,True
4,2019-02-03,1,C1,Ana Elias Borges Gonçalves,(11) 999557565,anaebgoncalves@gmail.com,ana.goncalves@cidadaopromundo.org,True

In [8]:
listas = f.carrega_listas()
listas.head()

,Nome,Desistência,Evasão,Situação,Obs,P1,P2,HW2,CP2,P3,...,Atraso,Ausencia,Total_Presença,HW_Fez,HW_Parcial,HW_Nao,Total_Homework,Nota_Participacao,Nota_Speaking,Turma
Código,,,,,,,,,,,,,,,,,,,,,
320191049,Ana Carolina Ribeiro dos Santos,,Sim,Reprovado,,Present,Present,None,10,Absent,...,0,7,0.25,0,1,4,0.0625,3.3333333333333335,7,A1
320191032,Clayvon da Silva Casado,,Não,Reprovado,,Present,Present,None,10,Present,...,3,2,0.46875,3,1,1,0.4375,9.166666666666666,9,A1
320191040,Daniele Santos Silva Basilio,,Não,Reprovado,,Present,Present,None,8,Present,...,0,2,0.5625,4,1,0,0.5625,7.25,7.5,A1
320191025,Eliane Alves Ferreira Pires,,Não,Reprovado,,Present,Present,None,7,Present,...,0,3,0.5,2,0,3,0.25,3.5,6,A1
320191057,Felipe Kenui Gomes da Silva,,Não,Reprovado,,Present,Present,None,9,Present,...,0,0,0.6875,3,1,1,0.4375,7.25,6.5,A1

In [9]:
listas = listas[listas.Evasão == "Não"]
listas = listas[listas.Desistência == ""]
listas = listas[listas.Obs == ""]

In [10]:
listas.head()

,Nome,Desistência,Evasão,Situação,Obs,P1,P2,HW2,CP2,P3,...,Atraso,Ausencia,Total_Presença,HW_Fez,HW_Parcial,HW_Nao,Total_Homework,Nota_Participacao,Nota_Speaking,Turma
Código,,,,,,,,,,,,,,,,,,,,,
320191032,Clayvon da Silva Casado,,Não,Reprovado,,Present,Present,None,10,Present,...,3,2,0.46875,3,1,1,0.4375,9.166666666666666,9,A1
320191040,Daniele Santos Silva Basilio,,Não,Reprovado,,Present,Present,None,8,Present,...,0,2,0.5625,4,1,0,0.5625,7.25,7.5,A1
320191025,Eliane Alves Ferreira Pires,,Não,Reprovado,,Present,Present,None,7,Present,...,0,3,0.5,2,0,3,0.25,3.5,6,A1
320191057,Felipe Kenui Gomes da Silva,,Não,Reprovado,,Present,Present,None,9,Present,...,0,0,0.6875,3,1,1,0.4375,7.25,6.5,A1
320191055,Jamile Lima da Silva,,Não,Reprovado,,Present,Present,None,10,Present,...,0,1,0.625,4,0,1,0.5,7.5,9.5,A1

## Define Aula a ser verificada e Filtra Lista de Presença

In [11]:
def checa_coluna(lista: pd.DataFrame,  coluna: str)-> bool:
    return sum(lista[coluna] == "") > 0

In [12]:
def checa_aula(lista: pd.DataFrame, aula: tuple)-> bool:
    check = 0
    for col in aula:
        if "SPK" not in col:
            check += int(checa_coluna(lista, col))
    return not bool(check)

In [15]:
for turma in TURMAS:
    df = listas[listas.Turma == turma]
    for i, aula in enumerate(AULAS[10:11]):
        if not checa_aula(df, aula):
            #display(alocação[alocação.Aula == str(i + 1)])
            display(df[["Nome", "Turma"] + list(aula)])

                                        Nome Turma      P11 HW11 CP11
Código
320191032            Clayvon da Silva Casado    A1   Absent
320191040       Daniele Santos Silva Basilio    A1   Absent
320191025        Eliane Alves Ferreira Pires    A1  Present
320191057        Felipe Kenui Gomes da Silva    A1  Present
320191055               Jamile Lima da Silva    A1  Present
320191043            Jéssica Osko de Almeida    A1   Absent
320191045                   Joyce Souza Lima    A1  Present
320191038          Milena Lais Leite Pereira    A1   Absent
320191041            Rafael Albuquerque Mori    A1  Present
320191034         Valéria Xavier de Oliveira    A1   Absent
320191061              Kennedy Sousa Pereira    A1  Present
320191063  Isabella Larocca Candido da Silva    A1   Absent

                                       Nome Turma        P11       HW11 CP11
Código
320161099               Elida Pereira Matos    B1    Present  Completed    8
320182035                Emelly Silva Sousa    B1    Present  Completed    7
320182032           Erik de Oliveira Morais    B1    Present  Completed    9
320182029       Felipe Cesar Peixoto Chagas    B1    Present               7
320182007             Guilherme Muniz Gomes    B1    Present               8
320182033   Joao Vitor Oliveira de Carvalho    B1  Late/Left  Completed    5
320182028   Laura Emilly Assunção Desidério    B1    Present  Completed    7
320182011      Mariana Mazzotto de Carvalho    B1     Absent               0
320182021            Mariele Sousa da Silva    B1     Absent               0
320182030  Matheus Henrique Araújo da Silva    B1    Present               7
320191059  Beatriz Larocca Candido da Silva    B1     Absent               0
320182027     Pamela Vitória Santos Sampaio    B1    Present               7

                                     Nome Turma        P11       HW11 CP11
Código
320182012   Ana Cristina Ribeiro Franklin    B2     Absent
320182024          Anderson Rego da Silva    B2    Present  Completed    9
320182002   Carlos Henrique Ribeiro Silva    B2    Present  Completed    8
320181019         Daniela Luana de Araujo    B2    Present  Completed   10
320161075       Estela Santiago de Araujo    B2    Present  Completed    8
320182034      Franciele Raucci Rodriguez    B2    Present  Completed    7
320182008             Diego de Souza Lima    B2    Present  Completed    8
320162027     Francisco Balbino Rodrigues    B2  Late/Left  Completed    7
320161077      Laercio Sebastião da Silva    B2    Present  Completed    8
320182022        Luciana dos Reis Ribeiro    B2    Present  Completed    7
120182026         Marcio Rogerio da Silva    B2    Present  Completed    9
320182014  Maria Aparecida Isaías de Lima    B2    Present  Completed    8
320182013            Rodrigo Franca Paiva    B2     Absent
320181026                 Rute Dias Nunes    B2    Present     Undone    8
320191058          Jorge Lopes Viana da S    B2    Present  Completed    9

                                        Nome Turma P11 HW11 CP11
Código
320162002     Ana Clara Verginassi de Morais    C1
320181038                   Ana Flavia Silva    C1
320181009      Caio Antônio Frazato da Silva    C1
320162023    Emilie Barbara Huanca Gutierrez    C1
320181043            Guilherme Lima Cordeiro    C1
320161185       Juan Carlos Nascimento Costa    C1
320191026              Manoela Santana Ramos    C1
320181039      Marcos Vinicius Peixe Miranda    C1
320191029  Patrick Valentin dos Santos Gneka    C1
320181042               Rafael Lima Cordeiro    C1
320181030           Rayssa Kauane de Santana    C1
320181041              Ryan de Godoi Martins    C1

,Nome,Turma,P11,HW11,CP11
Código,,,,,
320172050,Carlos Henrique Frazato Dias,D1,Present,None,5
320172053,Carlos Henryque Santana Ferreira,D1,Present,Completed,5
320152028,Déborah Cristine da Silva Primo,D1,Present,Completed,6
320161014,Elias da nuel Oliveira da Costa,D1,Present,Completed,9
320172048,Geani dos Santos Rodrigues,D1,Present,Partial,6
320191016,João Caetano,D1,Present,Partial,8
320172051,Larissa Frazato da Silva,D1,Present,Completed,8
320161123,Lucas Alencar Silva,D1,Present,Completed,1
320152077,Maria Fernanda Vandequoque de Camargo Grigorio,D1,Present,Completed,7
320162052,Nicole Ribeiro Silva,D1,Present,Undone,7
320162081,Nubia de Magalhães Gonçalves,D1,Present,Completed,7
320162054,Otavio Henrique Franklin Paiva,D1,Absent,None,
320162058,Ryan Araujo Gois da Silva,D1,Present,Completed,3
320161188,Samira Salles Carvajal,D1,Present,Completed,9
320152105,Sthefany da Conceição Araujo da Silva,D1,Present,Completed,8

                                                Nome Turma P11 HW11 CP11
Código
320162004                 Andreia Aparecida de Jesus    D2
320182026                       Bruno Rego Fernandes    D2
320161097                Carmen Lúcia Silveira Couto    D2
320161072                     Clorilda Barboza Alves    D2
320172004  Daiana Aparecida Julião Boletini da Silva    D2
320162016         Danilo Alexandre Boletini da Silva    D2
320172027                   Gabriel de Sousa Pereira    D2
320161105                     Graciela Alves de Melo    D2
320172031                         Lais Ester Roveron    D2
320172052             Luan Tadeu Apolinario de Souza    D2
320161137                     Maria Solange da Silva    D2
320172039              Mauro Ricardo Souto do Amaral    D2
320172040    Sabrina L'man Siqueira Pereira da Silva    D2
320172007                   Thiago Patrick Rodrigues    D2

                                        Nome Turma P11 HW11 CP11
Código
320161187           Catharina Beatriz Santos    E1
320191001              Cleiton da Silva Dias    E1
320162033         Julia Araujo Gois da Silva    E1
320162082        Julia Verginassi de Andrade    E1
320162043               Lucas Figueredo Lima    E1
320162049   Mateus Johnson Boletini da Silva    E1
320152092    Pedro Henrique Almeida Carvalho    E1
320181045              Rafaela Ramos Santana    E1
320191036  Rafaella Campos da Silva Patricio    E1
320162084       Sophia Verginassi de Andrade    E1
320191047    Lucas Oliveira Novais de Araújo    E1
320152021      Camila Vitoria Silva Oliveira    E1

,Nome,Turma,P11,HW11,CP11
Código,,,,,
320161069,Alessandra de Alcantara Pereira,E2,Absent,,
320152017,Benedita Aparecida Cruz,E2,Present,Completed,5
320162007,Bianca Rodrigues Marcelino Portela,E2,Present,Partial,4
320162011,Cláudia Alessandra de Oliveira Balbino,E2,Absent,,
320191006,Daniele Ferreira dos Santos Thomazine,E2,Present,Completed,6
320161134,Ivanilda Maria Aparecida Gabriel,E2,Present,Completed,4
320191008,Milena Cristina Leite de Abreu,E2,Absent,,
320191009,Patricia Lima Fagundes,E2,Present,Completed,9
320191005,Sueli Rodrigues de Oliveira Lima,E2,Present,Completed,9.5
220181049,Sandro Teixeira de Oliveira,E2,,,

                                          Nome Turma      P11       HW11 CP11
Código
320182016             Andréia da Silva Pereira    F1  Present     Undone    7
320161190               Davi Henrique da Silva    F1  Present  Completed    9
320172063                  João Pedro de Sousa    F1  Present    Partial    6
320191020    Karen Cristina da llaqua da Silva    F1  Present  Completed   10
320161058      Katherine de Alcantara Ferreira    F1   Absent
320152060                 Laisla Costa Rovetta    F1  Present  Completed    6
320162038         Leonardo de Souza dos Santos    F1  Present  Completed    7
320152101      Selena Causso Santanna da Silva    F1  Present  Completed    8
320152103       Stela Causso Santanna da Silva    F1  Present     Undone    6
320152104  Stephanie Cristine Nascimento Costa    F1  Present     Undone    6
320152107                 Tabita Costa Rovetta    F1  Present  Completed    6
320152108             Tatiana Pereira de Paula    F1  Present    Partial    6

                                       Nome Turma        P11       HW11 CP11
Código
320191002  Ananda Carolina dos Santos Silva    F2     Absent     Undone
320191010         Cristiane Mendes da Penha    F2    Present     Undone
320181037              Ieda dos Reis Santos    F2    Present     Undone
320182017        Lucinda de Fatima Oliveira    F2     Absent     Undone
320161109         Maria de Camargo Grigorio    F2    Present    Partial
120151037       Maria Edvânia Silva Marques    F2  Late/Left     Undone
320191018              Maria Helena de Lima    F2    Present     Undone
320182018          Paulo Henrique de Castro    F2    Present  Completed
320161085      Tâmara Jordane Barros Galvez    F2    Present  Completed
320161045            Tatiane da Silva Costa    F2    Present     Undone
320191012             Vanessa da Silva Paim    F2     Absent     Undone

                                              Nome Turma      P11 HW11 CP11
Código
320172011                 Adriana da Silva Pereira     I  Present
320131181              Amanda Vieira Martins Silva     I  Present
320161154                    Beatriz Dias da Silva     I  Present
320161139              Camila Mazzotto de Carvalho     I   Absent
320162013            Cristiane Terra da Silva Bono     I  Present
320161133              Fabio Junior Ramos Silveira     I  Present
320161136                  Kaique dos Santos Silva     I  Present
320151008               Kennyo da Silva Nascimento     I  Present
320162036  Larissa Chrystie Assunção Nemeth Piffer     I   Absent
320152065              Lirieli Ferreira dos Santos     I  Present
320152100                   Sara Thais Silva Lopes     I  Present
320161138                  Vanessa Lima dos Santos     I   Absent
320161197     Yvone Matos de Oliveira Araujo Costa     I   Absent

,Nome,Turma,P11,HW11,CP11
Código,,,,,
320142065,Elizeth Rosangela da Silva,J,Absent,Completed,
320161155,Emilly da Silva Borges,J,Present,Undone,10
320161162,Joseane Cristina Barros Coelho,J,Present,Completed,8.5
320142014,Lucas Jubal Oliveira Balbino Rodrigues,J,Late/Left,Undone,9
320141064,Marina dos Santos Hernandez Torres,J,Present,Undone,10
320162066,Wanderson Ribeiro do Amaral,J,Absent,None,

                                             Nome   Turma P11 HW11 CP11
Código
320181006                 Ana Luiza Neris Santana  Teens2
320181011        Beatriz Julião Boletini da Silva  Teens2
320191024                 Beatriz Leandro Augusto  Teens2
320181010                   Elisa da Silva Borges  Teens2
320191027            Enzo Yago Fontini de Queiroz  Teens2
320181002                  Gabriel Paulo da Silva  Teens2
320191017          Giovanna Cristina Lima Monegat  Teens2
320191031            João Victor Ferreira Queiroz  Teens2
320191028                    Juan Silva de Araujo  Teens2
320181001                        Kauã Santos Lima  Teens2
320181042            Luiz Henrique Ramalho Coelho  Teens2
320181003          Marcela Nataly da Silva Santos  Teens2
320181014  Maria Eduarda Ferreira Santos da Silva  Teens2
320181005                 Mariana Coelho de Souza  Teens2
320181012                   Murilo Salles Pereira  Teens2
320181007               Samantha dos Santos Bispo  Teens2

In [80]:
alocação[alocação.Aula == "1"]

,Data,Aula,Turma,Nome,Telefone,Email Pessoal,Email CPM,Presente
0,2019-02-03,1,F2,Adriana Beltrão Dupita,(11) 984566623,adriana.dupita@gmail.com,adriana.dupita@cidadaopromundo.org,True
1,2019-02-03,1,I,Adriana Fernandes de Araújo,(11) 981615548,adrifaraujo@gmail.com,adriana.araujo@cidadaopromundo.org,True
2,2019-02-03,1,A2,Alexandre Santos de Pinho,(11) 996936609,alexandre.spinho@gmail.com,alexandre.pinho@cidadaopromundo.org,True
3,2019-02-03,1,C1,Allexandre Assis Bighetti,(11) 975346059,allexandrebighetti@hotmail.com,allexandre.bighetti@cidadaopromundo.org,True
4,2019-02-03,1,C1,Ana Elias Borges Gonçalves,(11) 999557565,anaebgoncalves@gmail.com,ana.goncalves@cidadaopromundo.org,True
5,2019-02-03,1,G,Ana Paula Trevelin Souza,(11) 944842937,ana.trevelin@rb.com,ana.trevelin@cidadaopromundo.org,True
6,2019-02-03,1,I,Anastasia Valentinovna Gorskaya,(11) 947222278,gorskayaa@yahoo.com,anastasia.gorskaya@cidadaopromundo.org,True
7,2019-02-03,1,B2,Angela Cristina Dittrich Cirino,(11) 971734321,angelaacdc@gmail.com,angela.cirino@cidadaopromundo.org,True
8,2019-02-03,1,EA,Angelica Constantino da Silva,(11) 961102716,angelicacdasilva97@gmail.com,angelica.silva@cidadaopromundo.org,True
9,2019-02-03,1,D2,Bianca de Carvalho Munhoz Silva,(11) 964482227,munhozbianca@hotmail.com,bianca.silva@cidadaopromundo.org,True
10,2019-02-03,1,EA,Bruna Dinardi,(11) 989223873,brunabd@gmail.com,bruna.dinardi@cidadaopromundo.org,True
11,2019-02-03,1,C1,Bruno Salama,(11) 991326936,salama.bruno@gmail.com,bruno.salama@cidadaopromundo.org,True
12,2019-02-03,1,F2,Camila Sayuri Matsumoto,(11) 987556666,camilasm.85@gmail.com,camila.matsumoto@cidadaopromundo.org,True
13,2019-02-03,1,EA,Caroline Naomi Okamoto,(11) 98023-8968,carolinenaomiokamoto@gmail.com,caroline.okamoto@cidadaopromundo.org,True
14,2019-02-03,1,D1,Charles Tung,(11) 964486846,charlestung8@gmail.com,charles.tung@cidadaopromundo.org,True
15,2019-02-03,1,F2,Cintia Sayuri Sawada,(11) 998093438,cintia_sawada@hotmail.com,cintia.sawada@cidadaopromundo.org,True
16,2019-02-03,1,B1,Damiane Andressa Castro Silveira,(11) 981810384,damiane@gmail.com,damiane.silveira@cidadaopromundo.org,True
17,2019-02-03,1,EA,David Takeshi Tavares Cavaguti,(11) 979993016,david.cavaguti@gmail.com,david.cavaguti@cidadaopromundo.org,True
18,2019-02-03,1,C1,Diana Arakaki,(11) 975412344,diana.m.arakaki@gmail.com,diana.arakaki@cidadaopromundo.org,True
19,2019-02-03,1,H,Eduardo da Silva Alves dos Santos,(11) 996561662,e.salves@gmail.com,eduardo.santos@cidadaopromundo.org,True
20,2019-02-03,1,A2,Élida Raquel Achete Drongek,(11) 981548140,elidaquel@yahoo.com.br,elida.drongek@cidadaopromundo.org,True
21,2019-02-03,1,EA,Emilia Galvão Almeida,(11) 940777500,emilia@weprintbrasil.com.br,emilia.almeida@cidadaopromundo.org,True
22,2019-02-03,1,B1,Erik Pereira da Silva,(11) 957554359,erik.silva.sony@gmail.com,erik.silva@cidadaopromundo.org,True
23,2019-02-03,1,B2,Evelyn Aniya,(11) 995728109,profevy.aniya@gmail.com,evelyn.aniya@cidadaopromundo.org,True
24,2019-02-03,1,D2,Fabíola Aline Tolentino,(11) 999674024,fabiola.tolentino@hotmail.com,fabiola.tolentino@cidadaopromundo.org,True
25,2019-02-03,1,E2,Felipe Bello Labiapari,(11) 956194625,felipelabi@gmail.com,felipe.labiapari@cidadaopromundo.org,True
26,2019-02-03,1,Teens2,Fernanda de Vilhena Franco,(11) 997164297,ferdvilhena@gmail.com,fernanda.franco@cidadaopromundo.org,True
27,2019-02-03,1,I,Fernanda Malaco,(11) 999014936,fm.malaco@gmail.com,fernanda.malaco@cidadaopromundo.org,True
28,2019-02-03,1,B1,Fernanda Neroni de Moura,(11) 997217760,fneronimoura@outlook.com,fernanda.neroni@cidadaopromundo.org,True
29,2019-02-03,1,EA,Filipe Souza Boa Sorte,(11) 996666616,filipeboasorte@outlook.com,filipe.sorte@cidadaopromundo.org,True
...,...,...,...,...,...,...,...,...
83,2019-02-03,1,A2,Monica Barbosa Alves Braga,(11) 941293332,moba-braga@hotmail.com,monica.braga@cidadaopromundo.org,True
84,2019-02-03,1,F1,Monique Vatanable Sato,(11) 97446-2972,moniquesato@gmail.com,monique.sato@cidadaopromundo.org,True
85,2019-02-03,1,H,Natalia de Souza Girnius,(11) 995604524,nagirnius@gmail.con,natalia.girnius@cidadaopromundo.org.br,True
86,2019-02-03,1,G,Natália Ferreira de Souza,(11) 989048705,f_s.nata@hotmail.com,natalia.souza@cidadaopromundo.org,True
87,2019-02-03,1,E1,Nathalia Cavalcante Teixeira,(11) 991568516,nath.ct@gmail.com,nathalia.teixeira@cidadaopromundo.org,True
88,2019-02-03,1,I,Octávio Alves Júnior,(11) 994349335,oalvesjr@hotmail.com,octavio.junior@cidadaopromundo.org,True
89,2019-02-03,1,E2,Patricia Delgado Ribeiro,(11) 963961524,patricinhadelgado@gmail.com,patricia.delgado@cidadaopromundo.org,True
90,2019-02-03,1,C2,Paula Tibiriçá Bon,(11) 999559545,paulatbon@gmail.com,paula.bon@cidadaopromundo.org,True
91,2019-02-03,1,F1,Pedro Victor Almeida,(11) 976165249,pedrovictoralmeid@gmail.com,pedro.almeida@cidadaopromundo.org,True
92,2019-02-03,1,H,Priscila Hasse Palharim,(11) 983913876,ppalharim@usp.br,priscila.palharim@cidadaopromundo.org,True
93,2019-02-03,1,EA,Rafael Garcia de Almeida,(11) 989440856,rafael.almeida@live.de,rafael.garcia@cidadaopromundo.org,True
94,2019-02-03,1,G,Rodolfo Morais,(11) 986614506,rodolfoamorais@hotmail.com,rodolfo.morais@cidadaopromundo.org,True
95,2019-02-03,1,C1,Rodrigo Pereira de Sousa,(11) 990185612,roderikopera@gmail.com,rodrigo.sousa@cidadaopromundo.org,True
96,2019-02-03,1,F2,Rômulo Barbosa Ribeiro,(11) 989462826,romulob.ribeiro@yahoo.com.br,romulo.ribeiro@cidadaopromundo.org,True
97,2019-02-03,1,EA,Ronaldo da Silva Alves Batista,(11) 960763687,ronaldokun@gmail.com,ronaldo.batista@cidadaopromundo.org,True
98,2019-02-03,1,C2,Ronaldo Silva de Fausto,(11) 982619706,ronaldo-fausto@uol.com.br,ronaldo.fausto@cidadaopromundo.org,True
99,2019-02-03,1,I,Sarah Guidelli Deamates,(11) 944880126,saguidelli@yahoo.com.br,sarah.deamates@cidadaopromundo.org,True
100,2019-02-03,1,G,Sebastian Krieger,(11) 996394630,skrieger15@bloomberg.net,sebastian.krieger@cidadaopromundo.org,True
101,2019-02-03,1,A2,Simone Kimura,(11) 995710188,sii.kimura@gmail.com,simone.kimura@cidadaopromundo.org,True
102,2019-02-03,1,E2,Sindel Borges,(11) 972744870,sindel.borges@gmail.com,sindel.borges@cidadaopromundo.org,True
103,2019-02-03,1,B2,Sirlei Lucia Kraczkowski,(19) 999585874,skraczkowski@bloomberg.net,sirlei.kraczkowski@cidadaopromundo.org,True
104,2019-02-03,1,E2,Tatiane de Brito Tanaka,(11) 953249423,brito.tatiane@gmail.com,tatiane.tanaka@cidadaopromundo.org,True
105,2019-02-03,1,EA,Tatiane Mendes Camillo,(11) 984871602,imeio.tmc@gmail.com,tatiane.camillo@cidadaopromundo.org,True
106,2019-02-03,1,D2,Thiago Timko Buschinelli,(11) 996599410,thiagotimko@hotmail.com,thiago.buschinelli@cidadaopromundo.org,True
107,2019-02-03,1,A1,Vanessa Ávila de Souza,(11) 977388773,vas.vanessaavila@gmail.com,vanessa.souza@cidadaopromundo.org,True
108,2019-02-03,1,C1,Victor Carnevalli Durigan,(11) 954368680,vcdurigan@hotmail.com,victor.durigan@cidadaopromundo.org,True
109,2019-02-03,1,C1,Victoria Pieroni de Castro,(11) 974212678,victoriapcastro1@gmail.com,victoria.castro@cidadaopromundo.org,True
110,2019-02-03,1,D2,Wanieska Torri,(11) 982373333,wanieska@icloud.com,wanieska.torri@cidadaopromundo.org,True
111,2019-02-03,1,E2,Wilson Roberto Brasileiro Costa,(11) 975531991,wrbcosta@gmail.com,wilson.costa@cidadaopromundo.org,True
112,2019-02-03,1,D1,Yasmin Riveli de Souza Freitas,(12) 991881480,yasminriveli@gmail.com,yasmin.riveli@cidadaopromundo.org,True

In [31]:
for t in TURMAS:
    df = listas[listas.Turma ==t]
    if checa_coluna(listas[listas.Turma ==t], p):
        display(df[["Turma", "Nome", p]])

          Turma                           Nome       P9
Código
320191042    A2                  Fernando Mori  Present
320191048    A2    Graziela Cardoso dos Santos  Present
320191030    A2       Isaac de Paula Rodrigues  Present
320191058    A2         Jorge Lopes Viana da S
320191051    A2           José Beógenes Morais   Absent
320191035    A2       Leidiane Mendes da Penha  Present
320191037    A2  Luiz Carlos Patricio de Souza  Present
320191056    A2           Mayara Silva Fontini   Absent
320191003    A2    Pedro Jorge da Silva Junior  Present
320191039    A2      Saionara da Silva Santana  Present
320191021    A2      Vânia Holubovski Nogueira   Absent
320191062    A2                 Felipe Larocca   Absent

          Turma                              Nome P9
Código
320182003    B1        Ariela Estéfane dos Santos
320182038    B1        Beatriz Letícia Lima Silva
320161099    B1               Elida Pereira Matos
320182035    B1                Emelly Silva Sousa
320182032    B1           Erik de Oliveira Morais
320182029    B1       Felipe Cesar Peixoto Chagas
320182007    B1             Guilherme Muniz Gomes
320182033    B1   Joao Vitor Oliveira de Carvalho
320182028    B1   Laura Emilly Assunção Desidério
320182011    B1      Mariana Mazzotto de Carvalho
320182021    B1            Mariele Sousa da Silva
320182030    B1  Matheus Henrique Araújo da Silva
320161041    B1            Renata Padilha Pereira
320191059    B1  Beatriz Larocca Candido da Silva
320182027    B1     Pamela Vitória Santos Sampaio

          Turma                                            Nome       P9
Código
320172050    D1                    Carlos Henrique Frazato Dias  Present
320172053    D1                Carlos Henryque Santana Ferreira  Present
320152028    D1                 Déborah Cristine da Silva Primo
320161014    D1                 Elias da nuel Oliveira da Costa
320172048    D1                      Geani dos Santos Rodrigues
320191016    D1                                    João Caetano
320172051    D1                        Larissa Frazato da Silva
320161123    D1                             Lucas Alencar Silva
320172056    D1                    Luiz Gustavo Caetano de Lima
320152070    D1                     Luiz Soares de Marco Junior
320152077    D1  Maria Fernanda Vandequoque de Camargo Grigorio
320162052    D1                            Nicole Ribeiro Silva
320162081    D1                    Nubia de Magalhães Gonçalves
320162054    D1                  Otavio Henrique Franklin Paiva
320162058    D1                       Ryan Araujo Gois da Silva
320161188    D1                          Samira Salles Carvajal
320152105    D1           Sthefany da Conceição Araujo da Silva

          Turma                                 Nome P9
Código
320182016    F1             Andréia da Silva Pereira
320161190    F1               Davi Henrique da Silva
320172063    F1                  João Pedro de Sousa
320191020    F1    Karen Cristina da llaqua da Silva
320161058    F1      Katherine de Alcantara Ferreira
320152060    F1                 Laisla Costa Rovetta
320162038    F1         Leonardo de Souza dos Santos
320152101    F1      Selena Causso Santanna da Silva
320152103    F1       Stela Causso Santanna da Silva
320152104    F1  Stephanie Cristine Nascimento Costa
320152107    F1                 Tabita Costa Rovetta
320152108    F1             Tatiana Pereira de Paula
320191019    F1          Yuri Henrique da Cruz Silva

            Turma                                    Nome       P9
Código
320181006  Teens2                 Ana Luiza Neris Santana  Present
320181011  Teens2        Beatriz Julião Boletini da Silva
320191024  Teens2                 Beatriz Leandro Augusto
320181010  Teens2                   Elisa da Silva Borges
320191027  Teens2            Enzo Yago Fontini de Queiroz
320181002  Teens2                  Gabriel Paulo da Silva
320191017  Teens2          Giovanna Cristina Lima Monegat
320191028  Teens2                    Juan Silva de Araujo
320181001  Teens2                        Kauã Santos Lima
320181003  Teens2          Marcela Nataly da Silva Santos
320181014  Teens2  Maria Eduarda Ferreira Santos da Silva
320181005  Teens2                 Mariana Coelho de Souza
320181012  Teens2                   Murilo Salles Pereira
320181007  Teens2               Samantha dos Santos Bispo

In [33]:
listas[listas.Turma == "A2"]

,Nome,Desistência,Evasão,Situação,Obs,P1,P2,HW2,CP2,P3,...,Atraso,Ausencia,Total_Presença,HW_Fez,HW_Parcial,HW_Nao,Total_Homework,Nota_Participacao,Nota_Speaking,Turma
Código,,,,,,,,,,,,,,,,,,,,,
320191042,Fernando Mori,,Não,Reprovado,,Present,Present,None,8,Present,...,0,0,0.625,4,0,0,0.5,7.666666666666667,5,A2
320191048,Graziela Cardoso dos Santos,,Não,Reprovado,,Present,Present,None,9,Present,...,0,2,0.5,3,0,1,0.375,7.166666666666667,3.75,A2
320191030,Isaac de Paula Rodrigues,,Não,Reprovado,,Present,Present,None,9,Present,...,0,0,0.625,4,0,0,0.5,7.833333333333333,6.9399999999999995,A2
320191058,Jorge Lopes Viana da S,,Não,Reprovado,,Present,Present,None,9.5,Present,...,0,3,0.25,2,0,2,0.25,4.625,4.5,A2
320191051,José Beógenes Morais,,Não,Reprovado,,Present,Present,None,9,Present,...,1,1,0.53125,3,0,1,0.375,7.166666666666667,7.1899999999999995,A2
320191035,Leidiane Mendes da Penha,,Não,Reprovado,,Present,Present,None,9,Present,...,0,1,0.5625,3,0,1,0.375,8.166666666666666,4.25,A2
320191037,Luiz Carlos Patricio de Souza,,Não,Reprovado,,Present,Present,None,8,Present,...,1,0,0.59375,4,0,0,0.5,8.333333333333334,7.1899999999999995,A2
320191056,Mayara Silva Fontini,,Não,Reprovado,,Present,Present,None,9,Present,...,0,1,0.5625,4,0,0,0.5,6.833333333333333,9.05,A2
320191003,Pedro Jorge da Silva Junior,,Não,Reprovado,,Present,Present,None,8,Present,...,0,2,0.5,3,1,0,0.4375,6.333333333333333,3.125,A2
320191039,Saionara da Silva Santana,,Não,Reprovado,,Present,Present,None,8,Present,...,0,0,0.625,4,0,0,0.5,8.333333333333334,8.6,A2
320191021,Vânia Holubovski Nogueira,,Não,Reprovado,,Present,Present,None,8,Present,...,0,4,0.375,2,0,2,0.25,3.5833333333333335,3.75,A2
320191062,Felipe Larocca,,Não,Reprovado,,Present,Present,None,9,Present,...,0,1,0.5625,5,0,0,0.625,0,9,A2

## Analisa preenchimento de Aula

In [26]:
turmas = {}
for t in TURMAS:
    turmas[t] = aula[aula.Turma == t]

### Presença em Branco

In [44]:
for df in turmas.values():
    print(df[p] == False)  
        #display(alocação[alocação["Aula"] == n])

Código
320191049    False
320191032    False
320191040    False
320191025    False
320191057    False
320191055    False
320191044    False
320191043    False
320191045    False
320191052    False
320191038    False
320191041    False
320191046    False
320191034    False
             False
320191061    False
320191063    False
Name: P9, dtype: bool
Código
320191054    False
320191042    False
320191048    False
320191030    False
320191053    False
320191033    False
320191058    False
320191051    False
320191035    False
320191037    False
             False
320181028    False
320191056    False
             False
320191003    False
             False
320191039    False
320191021    False
320191062    False
Name: P9, dtype: bool
Código
320182003    False
320182038    False
320161099    False
320182035    False
320182032    False
320182029    False
320182007    False
320182033    False
320182028    False
320182011    False
320182021    False
320182030    False
320181022    False
320161041    False
320191059    False
320182027    False
Name: P9, dtype: bool
Código
320182012    False
320182024    False
320182002    False
320182005    False
320181019    False
320161075    False
320182034    False
320182025    False
320182008    False
320162027    False
320172017    False
320161077    False
320182022    False
120182026    False
320182014    False
320181015    False
320182013    False
320181026    False
320162008    False
320191058    False
Name: P9, dtype: bool
Código
320162002    False
320181038    False
320181009    False
320162023    False
320181043    False
320161185    False
320191026    False
320181039    False
320161093    False
320191029    False
320181042    False
320181030    False
320181041    False
Name: P9, dtype: bool
Código
320182031    False
320181013    False
320191004    False
320172034    False
320161098    False
320161116    False
320191050    False
320181031    False
320181033    False
320181018    False
320161195    False
320181032    False
Name: P9, dtype: bool
Código
320172050    False
320172053    False
320152028    False
320161014    False
320172048    False
320151005    False
320191016    False
320172051    False
320161053    False
320161123    False
320172056    False
320152070    False
320152077    False
320162052    False
320162081    False
320162054    False
320162058    False
320161188    False
320152105    False
Name: P9, dtype: bool
Código
320191022    False
320162004    False
320181036    False
320182026    False
320161097    False
320161072    False
320172004    False
320162016    False
320172027    False
320191013    False
320161105    False
320181035    False
320172031    False
320172052    False
320161137    False
320172039    False
320172040    False
320172007    False
320172033    False
Name: P9, dtype: bool
Código
320161187    False
320191001    False
320162033    False
320162082    False
320162043    False
320162049    False
320152092    False
320181045    False
320191036    False
320162084    False
320191023    False
320191047    False
320152021    False
Name: P9, dtype: bool
Código
320161069    False
320191007    False
320152017    False
320162007    False
320162011    False
320191006    False
320172006    False
320161134    False
320191008    False
320191009    False
             False
320191005    False
220181049    False
Name: P9, dtype: bool
Código
320161087    False
320182016    False
320161190    False
320172063    False
320191020    False
320161058    False
320152060    False
320162038    False
320152101    False
320152103    False
320152104    False
320152107    False
320152108    False
320191019    False
Name: P9, dtype: bool
Código
320191002    False
320191010    False
320191014    False
320181037    False
320162031    False
320182017    False
320161109    False
120151037    False
320191018    False
320182018    False
320161085    False
320161045    False
320191012    False
320191015    False
Name: P9, dtype: bool
Código
320172062     False
320152004     False
320142011     False
320161088     False
320191011     False
1220161012    False
320182020     False
320162050     False
320162052     False
320161111     False
1220161017    False
320191060     False
320161064     False
Name: P9, dtype: bool
Código
320161160    False
320152025    False
320161179    False
320161016    False
320161118    False
320162030    False
320181029    False
320182004    False
320181027    False
320152073    False
320131084    False
320152093    False
Name: P9, dtype: bool
Código
320172011    False
320131181    False
320161154    False
320161139    False
320162013    False
320161133    False
320161136    False
320151008    False
320162036    False
320152065    False
320152100    False
320161138    False
320161197    False
Name: P9, dtype: bool
Código
320142065    False
320161155    False
320161162    False
320142014    False
320141064    False
320162066    False
320162066    False
Name: P9, dtype: bool
Código
320181006    False
320181011    False
320191024    False
320181010    False
320191027    False
320181002    False
320191017    False
320191031    False
320191028    False
320181001    False
320181042    False
320181003    False
320181014    False
320181005    False
320181012    False
320181007    False
Name: P9, dtype: bool

In [41]:
df.p

AttributeError: 'DataFrame' object has no attribute 'p'

In [40]:
labels = ["B1", "D1", "F1", "Teens2"]

for t in labels:
    display(alocação[alocação.Turma == t])

,Data,Aula,Turma,Nome,Telefone,Email Pessoal,Email CPM,Presente
16,2019-02-03,1,B1,Damiane Andressa Castro Silveira,(11) 981810384,damiane@gmail.com,damiane.silveira@cidadaopromundo.org,True
22,2019-02-03,1,B1,Erik Pereira da Silva,(11) 957554359,erik.silva.sony@gmail.com,erik.silva@cidadaopromundo.org,True
28,2019-02-03,1,B1,Fernanda Neroni de Moura,(11) 997217760,fneronimoura@outlook.com,fernanda.neroni@cidadaopromundo.org,True
44,2019-02-03,1,B1,Iuri de Mendonça Cruz,(11) 994678477,iuri.mc@hotmail.com,iuri.cruz@cidadaopromundo.org,True
50,2019-02-03,1,B1,Juliana Guedes Ribeiro Santos,(12) 988727462,juhguedes.mail@gmail.com,juliana.guedes@cidadaopromundo.org,True
117,2019-02-10,2,B1,Iuri de Mendonça Cruz,(11) 994678477,iuri.mc@hotmail.com,iuri.cruz@cidadaopromundo.org,True
118,2019-02-10,2,B1,Juliana Guedes Ribeiro Santos,(12) 988727462,juhguedes.mail@gmail.com,juliana.guedes@cidadaopromundo.org,True
154,2019-02-17,3,B1,Fernanda Neroni de Moura,(11) 997217760,fneronimoura@outlook.com,fernanda.neroni@cidadaopromundo.org,True
155,2019-02-17,3,B1,Erik Pereira da Silva,(11) 957554359,erik.silva.sony@gmail.com,erik.silva@cidadaopromundo.org,True
191,2019-02-24,4,B1,Diego Cintra Silva,(11) 962535559,dcintra8@gmail.com,diego.cintra@cidadaopromundo.org,True
192,2019-02-24,4,B1,Erik Pereira da Silva,(11) 957554359,erik.silva.sony@gmail.com,erik.silva@cidadaopromundo.org,True
193,2019-02-24,4,B1,Iuri de Mendonça Cruz,(11) 994678477,iuri.mc@hotmail.com,iuri.cruz@cidadaopromundo.org,True

,Data,Aula,Turma,Nome,Telefone,Email Pessoal,Email CPM,Presente
14,2019-02-03,1,D1,Charles Tung,(11) 964486846,charlestung8@gmail.com,charles.tung@cidadaopromundo.org,True
32,2019-02-03,1,D1,Gabriela de Souza Labella,(11) 985741352,gabi.labella@hotmail.com,gabriela.labella@cidadaopromundo.org,True
38,2019-02-03,1,D1,Heitor Gomes de Araujo e Castro,(11) 999549400,heitoraraujo@gmail.com,heitor.castro@cidadaopromundo.org,True
74,2019-02-03,1,D1,Maria Musumeci Sandim,(12) 997010869,maria.msandim@gmail.com,maria.sandim@cidadaopromundo.org,True
78,2019-02-03,1,D1,Marina Braga,(11) 941103332,marinaalvesbraga@gmail.com,marina.braga@cidadaopromundo.org,True
112,2019-02-03,1,D1,Yasmin Riveli de Souza Freitas,(12) 991881480,yasminriveli@gmail.com,yasmin.riveli@cidadaopromundo.org,True
125,2019-02-10,2,D1,Charles Tung,(11) 964486846,charlestung8@gmail.com,charles.tung@cidadaopromundo.org,True
126,2019-02-10,2,D1,Wellington Fernando Silva Almeida,(11) 974520890,wellingtonnandof@gmail.com,wellington.almeida@cidadaopromundo.org,True
162,2019-02-17,3,D1,Maria Musumeci Sandim,(12) 997010869,maria.msandim@gmail.com,maria.sandim@cidadaopromundo.org,True
163,2019-02-17,3,D1,Wellington Fernando Silva Almeida,(11) 974520890,wellingtonnandof@gmail.com,wellington.almeida@cidadaopromundo.org,True
203,2019-02-24,4,D1,Heitor Gomes de Araujo e Castro,(11) 999549400,heitoraraujo@gmail.com,heitor.castro@cidadaopromundo.org,True
204,2019-02-24,4,D1,Maria Musumeci Sandim,(12) 997010869\tmaria.msandim@gmail.com\tmaria...,NaN,NaN,True

,Data,Aula,Turma,Nome,Telefone,Email Pessoal,Email CPM,Presente
33,2019-02-03,1,F1,Gabriela Moledo de Carvalho,(11) 992576075,gabilink@gmail.com,gabriela.carvalho@cidadaopromundo.org,True
68,2019-02-03,1,F1,Marcelo Cazarine de Oliveira,(11) 941856593,marcelocazarine@hotmail.com,marcelo.oliveira@cidadaopromundo.org,True
84,2019-02-03,1,F1,Monique Vatanable Sato,(11) 97446-2972,moniquesato@gmail.com,monique.sato@cidadaopromundo.org,True
91,2019-02-03,1,F1,Pedro Victor Almeida,(11) 976165249,pedrovictoralmeid@gmail.com,pedro.almeida@cidadaopromundo.org,True
137,2019-02-10,2,F1,Pedro Victor Almeida,(11) 976165249,pedrovictoralmeid@gmail.com,pedro.almeida@cidadaopromundo.org,True
138,2019-02-10,2,F1,Carolina Maruyama,(11) 954449995,carolinamaruyama@yahoo.com.br,carolina.maruyama@cidadaopromundo.org,True
171,2019-02-17,3,F1,Carolina Maruyama,(11) 954449995,carolinamaruyama@yahoo.com.br,carolina.maruyama@cidadaopromundo.org,True
172,2019-02-17,3,F1,Annally Lima,(11) 963525090,annally.alima@gmail.com,annally.lima@cidadaopromundo.org,True
217,2019-02-24,4,F1,Pedro Victor Almeida,(11) 976165249,pedrovictoralmeid@gmail.com,pedro.almeida@cidadaopromundo.org,True
218,2019-02-24,4,F1,Marcelo Cazarine de Oliveira,(11) 941856593,marcelocazarine@hotmail.com,marcelo.oliveira@cidadaopromundo.org,True
219,2019-02-24,4,F1,Annally Lima,(11) 963525090,annally.alima@gmail.com,annally.lima@cidadaopromundo.org,True

,Data,Aula,Turma,Nome,Telefone,Email Pessoal,Email CPM,Presente
26,2019-02-03,1,Teens2,Fernanda de Vilhena Franco,(11) 997164297,ferdvilhena@gmail.com,fernanda.franco@cidadaopromundo.org,True
36,2019-02-03,1,Teens2,Giulia Falkine,(11) 981848599,giulia.falkine@gmail.com,giulia.falkine@cidadaopromundo.org,True
43,2019-02-03,1,Teens2,Isabela Gardenal Ometto,(11) 947586911,omettoisabela@gmail.com,isabela.ometto@cidadaopromundo.org,True
52,2019-02-03,1,Teens2,Karoline Costa Ribeiro,(11) 986411098,karoline-costa@hotmail.com,karoline.ribeiro@cidadaopromundo.org,True
55,2019-02-03,1,Teens2,Larissa de Oliveira Souza,(11) 996662654,lara_osouza@hotmail.com,larissa.souza@cidadaopromundo.org,True
56,2019-02-03,1,Teens2,Laura Dela Antonio Barbosa,(11) 955592210,lauradelaantonio@gmail.com,laura.barbosa@cidadaopromundo.org,True
59,2019-02-03,1,Teens2,Ligia Battaglia Deméo,(11) 931001207,ligiabattaglia@hotmail.com,ligia.demeo@cidadaopromundo.org,True
148,2019-02-10,2,Teens2,Marilia Machado Muchiuti,(11) 982579903,marilia_muchiuti@hotmail.com,marilia.muchiuti@cidadaopromundo.org,True
149,2019-02-10,2,Teens2,Wellington Santos Galvao da Silva,(11) 968226605,wellingtonsgalvao@yahoo.com,wellington.silva@cidadaopromundo.org,True
182,2019-02-17,3,Teens2,Giulia Falkine,(11) 981848599,giulia.falkine@gmail.com,giulia.falkine@cidadaopromundo.org,True
183,2019-02-17,3,Teens2,Milena Aparecida dos Santos,(11) 998770822,milena.asantos13@gmail.com,milena.santos@cidadaopromundo.org,True
184,2019-02-17,3,Teens2,Isabela Gardenal Ometto,(11) 947586911,omettoisabela@gmail.com,isabela.ometto@cidadaopromundo.org,False
185,2019-02-17,3,Teens2,Laura Dela Antonio Barbosa,(11) 955592210,lauradelaantonio@gmail.com,laura.barbosa@cidadaopromundo.org,True
232,2019-02-24,4,Teens2,Larissa de Oliveira Souza,(11) 996662654,lara_osouza@hotmail.com,larissa.souza@cidadaopromundo.org,True
233,2019-02-24,4,Teens2,Isabella Gardenal Ometto,(11) 947586911,omettoisabela@gmail.com,isabela.ometto@cidadaopromundo.org,True
234,2019-02-24,4,Teens2,Ligia Battaglia Deméo,(11) 931001207,ligiabattaglia@hotmail.com,ligia.demeo@cidadaopromundo.org,True

In [118]:
desist = (~listas.Desistência.isnull()) & (listas.Presença != '0')
obs = listas.Obs.isnull()

listas.loc[(desist & obs), ["Turma", "Nome", "Presença", "Obs"]]

          Turma                              Nome Presença  Obs
Código
320191054    A2                  Fernanda Bezerra        1  NaN
320191053    A2               Jair Armando Chaves        2  NaN
320191033    A2  Jaqueline Maria Souza de Almeida        2  NaN
320182025    B2           Francielle Campos Silva        1  NaN
320191022    D2     Ana Caroline de Oliveira Lima        1  NaN

In [95]:
listas.loc[listas.Evasão == "Sim",["Turma", "Nome", "Presença"]]

          Turma                           Nome Presença
Código
320181032    C2           Wesley Silva Olimpio        0
320191022    D2  Ana Caroline de Oliveira Lima        1
320191013    D2        Giulia Almeida da Silva        0
320181035    D2      Iolanda dos Reis de Souza        0
320182004     H                 Isabela Borges        0

In [ ]:
def preenche_lacunas(planilhas_de_presença):

    for k, (sh, df) in planilhas_de_presença.items():

        print("Processing: {}\n".format(k))

        print(110*"=")

        for item in f.AULAS:

            if isinstance(item, tuple):

                p, hw, cp = item

                t1 = ((df[p] == "NO") & (df[hw] == ""))

                t2 = ((df[p] == "NO") & (df[cp] == ""))                
                                
                if df.loc[t2].shape[0]:
                    
                    display(df.loc[t2])

                df.loc[t1, hw] = "N"
                
                if "SPK" in cp:
                    
                    df.loc[t2, cp] = "0"
                    
                else:

                    df.loc[t2, cp] = "N/A"
                    
                df.loc[df[hw] == "+/-", hw] = "'+/-"
                
                df.loc[df[hw] == "½", hw] = "'+/-"
                
                df.loc[df[hw] == "1/2", hw] = "'+/-"
        
        #corrige_preenchimento(sh, df, 7, 32)

In [ ]:
alunos = pd.DataFrame(columns=["Turma", "Nome", "P_15", "Nota_Final"])

for k, (sh, df) in planilhas_de_presença.items():
    print(k)
    p = ((df["P_15"] != "YES") & (df["Nome"] != ""))
    df["Turma"] = k
    subset = df.loc[:, ["Nome", "P_15","Nota_Final", "Turma"]][p]
    alunos = alunos.append(subset)

### Checar Presença

In [ ]:
iterator = iter(planilhas_de_presença.items())

In [ ]:
k, (sh, df) = next(iterator)

print("Turma: " + k)
for item in f.AULAS:

    if isinstance(item, tuple) and len(item) == 3:

        p, hw, cp = item

        t1 = ((df[p] == "NO") & (df[hw] == ""))

        t2 = ((df[p] == "YES") & (~df[hw].isin(["Y", "N", "+/-", "N/H"])))

        t3 = ((df[p] == "NO") & (df[cp] == ""))

        t4 = ((df[p] == "YES") & (~df[cp].isin(["A", "B", "C", "N/A"])))
        
        
        if df.loc[t1].shape[0]:

            print('Falta sem nota de Homework\n')

            display(df.loc[t1, ["Nome",p,hw,cp]])

            df.loc[t1, hw] = "N/H"

        if df.loc[t2].shape[0]:

            print("Presença sem Nota de Homework\n")

            display(df.loc[t2, ["Nome",p,hw,cp]])

            df.loc[t2, hw] = "Y"

        if df.loc[t3].shape[0]:

            print("Falta sem nota de Participação\n")

            display(df.loc[t3, ["Nome",p,hw,cp]])

            if "SPK" not in cp:

                df.loc[t3, cp] = "N/A"
            

        if df.loc[t4].shape[0]:

            print("Presença sem nota de Participação")

            display(df.loc[t4, ["Nome",p,hw,cp]])

            if "SPK" not in cp:

                df.loc[t4, cp] = "A"
                

            
#t5 = ((df['P_8'] == "") | (df['P_8'] == 'NO') & (df['Nota_Mid'] != '0.00'))
              
#t6 = ((df['P_15'] == "") | (df['P_15'] == 'NO') & (df['Nota_Final'] != '0.00'))
                
                
#if df.loc[t5].shape[0]:

#    print(k)

#    display(df.loc[t5, ["Nome",p, "Nota_Mid"]])

#    df.loc[t5, ["P_8", "Nota_Mid"]] = ["NO", "0.00"]

#if df.loc[t6].shape[0]:

#    print(k)

#    display(df.loc[t6, ["Nome",p, "Nota_Final"]])

#    df.loc[t6, ["P_15", "Nota_Final"]] = ["NO", "0.00"]

df["Nota_Mid"] = df["Nota_Mid"].str.replace(",", ".")
df["Nota_Final"] = df["Nota_Final"].str.replace(",", ".")


corrige_preenchimento(sh, df, 7, 54)

In [ ]:
notas_dos_alunos = {}

for nome, turma in turmas.items():

    sh, df = f.load_sheet_from_workbook(turma, 'Notas dos Alunos', skiprows=[1,2,3,4])
    
    display(df)

    lista = pd.DataFrame(columns=df.columns)

    registros = sh.get_all_values()

    #lista = f.nomeia_cols_lista(lista)

    notas_dos_alunos[nome.split("_")[-1]] = df
    
    break

In [ ]:
df.head()

In [ ]:
colunas_1 = ["Nome", "P_8", "Nota_Mid"]

colunas_2 = colunas_1 + ["Turma"]

notas_mid = pd.DataFrame(columns=colunas_2)

for k, (sh, df) in iterator:
    
    df["Turma"] = k
        
    notas_mid = notas_mid.append(df[df["Nome"] != ""][colunas_2])

In [ ]:
notas_mid.to_csv("Relatorio_Mid.csv", index=False)

In [ ]:
aula = "Aula 11"

colunas = ["Nome", "Nota_Mid"]

k, (sh, df) = next(iterator)
    
print("Processing: {}\n".format(k))

filtro = (agenda["Aula"].str.contains(aula)) & (agenda["Turma"] == k)

professores = agenda[filtro]

print("Professores: \n", professores[["Nome", "Email CPM", "Email Pessoal"]])

criterio = (df["Nome"] != "")

display(df[criterio][colunas])

In [ ]:
agenda[agenda["Aula"].str.contains("11")]

In [ ]:
alocacao[alocacao["Aula"].str.contains("12")]

In [ ]:
for key, (sh, df) in planilhas_de_presença.items():
    print(key)
    display(df[["P_9", "HW_9", "CP_9"]])

In [ ]:
presença = {}
for sh, wks in zip(planilhas, listas_de_presenças):
    presença[sh.title] = wks[1].range("Q4:S25")

In [ ]:
presença = {}
for sh, wks in zip(planilhas, listas_de_presenças): 
    presença[sh.title] = wks[1]

In [ ]:
for plan in presença.values():
    plan["Aula 4 (Speaking)"]

In [ ]:
for key, value in presença.items():
    print(key)
    print("\n")
    for v in value:
        print(v.value)
    print("\n")

In [ ]:
desistencia = pd.DataFrame(columns = listas_de_presenças[0].columns)
for lista in listas_de_presenças:
    desistencia = lista['Desistência'] == 'Sim'
    print(lista[desistencia][['Código', 'NOME COMPLETO', "Desistência", "Evasão"]])

In [ ]:
presença = []

for lista in listas_de_presenças:
    print("Planilha: {}, Coluna BC: {}".format(lista[0].title, lista[0].range("BC1:BC25")))

In [ ]:
presença[0]

In [ ]:
count = []

for turma in presença:
    for i, aluno in enumerate(turma[0]):
        if aluno.value == r'':
            next
        elif turma[1][i].value == r'0%':
            count.append(aluno.value)

In [ ]:
count

In [ ]:
counts = agenda.iloc[:184]["Nome"].value_counts()

In [ ]:
counts

#### Merge the Teachers Info from all Spreadsheets into one

In [ ]:
#for i in skills[0]:
#    key = aula.cell(i, 1).value
#    value = aula.cell(i, 2).value
#    dict_[key] = value
    
#print(dict_exs)